#!/usr/bin/env bash
# arch-guard.sh — enforces .claude/rules/flutter-architecture.md
#
# Reads a hook payload on stdin: {"tool_input":{"file_path":"/abs/path/x.dart"}}
# Exit 0 = allowed. Exit 2 = violation (message on stderr).
#
# Scope: modules/*/lib/**/*.dart only. packages/**, root lib/** and test/** are
# out of scope — they follow different conventions (see rules §9, §10).
#
# The RULES block below is generated mechanically from the table in
# .claude/rules/flutter-architecture.md §1. That file is this script's spec: the
# check list is §2, the opt-out markers §3, and §4 is what a new check must pass.
#
# All content checks run against a comment-stripped copy of the file, so a rule
# never fires on commented-out code.

set -uo pipefail

# "path_marker|allowed_file_suffixes|matching_class_suffixes"
# Suffix lists are positional: the Nth file suffix requires the Nth class suffix.
# Markers starting with @ are positional (not path substrings).
RULES=(
  "@src_root|_container,_factory|Container,Factory"
  "@presentation_root|_page,_sheet,_dialog,_widget|Page,Sheet,Dialog,Widget"
  "/src/data/models/|_model|Model"
  "/src/data/datasource/|_source,_impl,_api_paths,_datasource|Source,Impl,ApiPaths,DataSource"
  "/src/data/repository/|_impl|RepositoryImpl"
  "/src/domain/repository/|_repository|Repository"
  "/src/domain/interactor/|_interactor|Interactor"
  "/src/di/|_injection|Injection"
  "/src/router/|_router|Router"
  "/bloc/|_bloc,_event,_state|Bloc,Event,State"
  "/mixin/|_mixin|Mixin"
  "/args/|_args|Args"
)

payload=$(cat)
file_path=$(printf '%s' "$payload" | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')

[ -z "$file_path" ] && exit 0
[ -f "$file_path" ] || exit 0

# --- 0. pubspec: modules/* must not depend on modules/* -----------------------
case "$file_path" in
  */modules/*/pubspec.yaml)
    self=$(printf '%s' "${file_path#"$PWD"/}" | cut -d/ -f2)
    if [ -d modules ]; then
      others=$(ls modules | grep -v "^${self}$" | tr '\n' '|' | sed 's/|$//')
      [ -n "$others" ] && grep -qE "^[[:space:]]+($others):" "$file_path" && {
        echo "arch-guard: ${file_path#"$PWD"/}" >&2
        echo "  modules/* must not depend on modules/* -> ModuleInteractor / PageFactory / WidgetFactory" >&2
        exit 2
      }
    fi
    exit 0
    ;;
  */packages/*/pubspec.yaml)
    self=$(printf '%s' "${file_path#"$PWD"/}" | cut -d/ -f2)
    # merge_dependencies is the one package that assembles the app out of modules.
    if [ "$self" != merge_dependencies ] && [ -d modules ]; then
      mods=$(ls modules | tr '\n' '|' | sed 's/|$//')
      [ -n "$mods" ] && grep -qE "^[[:space:]]+($mods):" "$file_path" && {
        echo "arch-guard: ${file_path#"$PWD"/}" >&2
        echo "  packages/* must not depend on modules/* -> only merge_dependencies may" >&2
        exit 2
      }
    fi
    exit 0
    ;;
esac

case "$file_path" in
  *.dart) ;;
  *) exit 0 ;;
esac

rel=${file_path#"$PWD"/}

# --- scope -------------------------------------------------------------------
# Two zones with different rule sets. `modules` gets the full list; `packages`
# gets the subset that holds there today with zero violations (rules §11) —
# a shared package legitimately owns what a module may not touch (Theme.of in
# the theme extension, EdgeInsets in Dimensions, Navigator in a page route).
case "$rel" in
  modules/*/lib/*) zone=modules ;;
  packages/*/lib/*) zone=packages ;;
  *) exit 0 ;;
esac
case "$rel" in
  */test/*|*_test.dart|*/test_helpers/*) exit 0 ;;
  # a plugin's example/ is a standalone demo app, not part of the package API.
  packages/*/example/*) exit 0 ;;
  # generated by flutter gen-l10n; regenerated on every key, never hand-edited.
  packages/core/lib/src/l10n/app_localizations*.dart) exit 0 ;;
esac

base=$(basename "$rel" .dart)
fail() { echo "arch-guard: $rel" >&2; echo "  $1" >&2; exit 2; }

# --- opt-out --------------------------------------------------------------
# A parked feature keeps its code in the tree while the rules cannot apply to it.
# Such a file opts out with a first-line marker carrying the reason:
#
#   // arch-guard: ignore — parked feature
#
if head -3 "$file_path" | grep -qE '^// arch-guard: ignore[[:space:]]+[^[:space:]]'; then
  exit 0
fi

# A single grandfathered rule opts out by id:
#
#   // arch-guard: allow l10n-text — brand name, never translated
#
# Ids in use: l10n-text, bloc-mutable, bloc-public-dep, build-when, import-order.
allow() {
  grep -qE "^// arch-guard: allow $1[[:space:]]+[^[:space:]]" "$file_path"
}

# Comment-stripped copy — every content check reads this, never the raw file.
code=$(mktemp -t arch-guard)
trap 'rm -f "$code"' EXIT
sed -E 's@^[[:space:]]*//.*$@@' "$file_path" > "$code"

has_decl() { # $1 = class-name suffix; case-insensitive
  grep -qiE '^[a-z ]*(class|mixin|enum|typedef|extension) [A-Za-z0-9_]*'"$1"'\b' "$code"
}

# --- 1. structure: file suffix + class suffix (rules §2) — modules only -------
matched=""
[ "$zone" = modules ] && for rule in "${RULES[@]}"; do
  marker=${rule%%|*}
  rest=${rule#*|}
  suffixes=${rest%%|*}
  classes=${rest##*|}

  case "$marker" in
    @src_root)
      # modules/<m>/lib/src/<file>.dart — nothing between src/ and the file
      [[ "$rel" =~ ^modules/[^/]+/lib/src/[^/]+\.dart$ ]] || continue
      ;;
    @presentation_root)
      # modules/<m>/lib/src/presentation/<feature>/<file>.dart
      [[ "$rel" =~ ^modules/[^/]+/lib/src/presentation/[^/]+/[^/]+\.dart$ ]] || continue
      # presentation/widgets/ is the module-wide shared widget bucket, not a feature
      [[ "$rel" =~ ^modules/[^/]+/lib/src/presentation/widgets/ ]] && continue
      ;;
    *)
      case "$rel" in *"$marker"*) ;; *) continue ;; esac
      ;;
  esac

  matched="$marker"
  IFS=',' read -r -a sfx <<< "$suffixes"
  IFS=',' read -r -a cls <<< "$classes"

  hit=-1
  for i in "${!sfx[@]}"; do
    case "$base" in *"${sfx[$i]}") hit=$i; break ;; esac
  done

  if [ "$hit" -lt 0 ]; then
    fail "file name must end with one of: ${suffixes//,/.dart, }.dart"
  fi
  if ! has_decl "${cls[$hit]}"; then
    fail "'${sfx[$hit]}.dart' must declare a class/mixin ending in '${cls[$hit]}'"
  fi
  break
done

# --- 2. bloc specifics (rules §4) --------------------------------------------
case "$rel" in
  modules/*/bloc/*) bloc_scope=1 ;;
  *) bloc_scope=0 ;;
esac
[ "$bloc_scope" = 1 ] && case "$base" in
  *_bloc)
    grep -qE "^part '" "$code" \
      || fail "_bloc.dart must 'part' its _event.dart and _state.dart"
    if grep -qE '\bon<[A-Za-z0-9_]+>\(' "$code" \
       && [ "$(grep -cE '\bon<[A-Za-z0-9_]+>\(' "$code")" -ne "$(grep -c 'transformer:' "$code")" ]; then
      fail "every on<Event>() needs an explicit transformer:"
    fi
    while IFS= read -r h; do
      case "$h" in *Handler) ;; *) fail "bloc handler '$h' must be named _<verb><target>Handler" ;; esac
    done < <(grep -ohE '\bon<[A-Za-z0-9_]+>\([[:space:]]*_[A-Za-z0-9_]+' "$code" | sed -E 's/.*\([[:space:]]*//')
    ;;
  *_event|*_state)
    grep -qE '^part of ' "$code" || fail "$base.dart must be 'part of' its bloc"
    grep -qE '^sealed class ' "$code" || fail "$base.dart root type must be a 'sealed class'"
    ;;
esac

# --- 3. mixin shape (rules §2) -----------------------------------------------
[ "$zone" = modules ] && case "$base" in
  *_mixin)
    grep -qE '^mixin [A-Za-z0-9_]+Mixin on State<' "$code" \
      || fail "must be declared as 'mixin <Name>Mixin on State<...>'"
    ;;
esac

# --- 4. imports (rules §3) ---------------------------------------------------
grep -qE "^import '(\.\./|\./)" "$code" \
  && fail "relative imports are forbidden in lib/ — use package: imports"

self=$(printf '%s' "$rel" | cut -d/ -f2)

pkgs="core components navigation platform_methods merge_dependencies"
[ "$zone" = packages ] && pkgs=$(printf '%s\n' $pkgs | grep -v "^${self}$")
foreign=$(printf '%s\n' $pkgs | tr '\n' '|' | sed 's/|$//')
grep -qE "^import 'package:($foreign)/src/" "$code" \
  && fail "never import another package's src/ — use its barrel (package:core/core.dart)"

# merge_dependencies is the assembler: it is the only place that names modules.
if [ "$zone" = modules ] || { [ "$zone" = packages ] && [ "$self" != merge_dependencies ]; }; then
  if [ -d modules ]; then
    others=$(ls modules | grep -v "^${self}$" | tr '\n' '|' | sed 's/|$//')
    [ -n "$others" ] && grep -qE "^import 'package:($others)/" "$code" \
      && if [ "$zone" = modules ]; then
        fail "modules/* must never import another module — use ModuleInteractor / PageFactory / WidgetFactory"
      else
        fail "packages/* must never import a module — only merge_dependencies may"
      fi
  fi
fi

grep -qE "^import 'package:flutter/material\.dart'" "$code" \
  && fail "use package:material_ui/material_ui.dart instead of package:flutter/material.dart"

# --- 5. banned APIs (rules §5, §6, §7) ---------------------------------------
ban() { grep -qE "$1" "$code" && fail "$2"; return 0; }

# Both zones.
ban '(^|[^A-Za-z0-9_.])MediaQuery\.of\('        "MediaQuery.of() -> context.width / context.height / context.padding"
ban '(^|[^a-zA-Z_.])(print|debugPrint)\('       "print()/debugPrint() -> logMessage('...', error: e, stackTrace: s)"
ban '(^|[^A-Za-z0-9_.])(fromJson|toJson)\b'     "fromJson/toJson -> fromMap/toMap"

# Modules only:
if [ "$zone" = modules ]; then
  ban '(^|[^A-Za-z0-9_.])Theme\.of\('             "Theme.of() -> context.color / context.textStyle"
  ban '(^|[^A-Za-z0-9_.])EdgeInsets\.all\('       "EdgeInsets.all() -> Dimensions.kPaddingAll*"
  ban '(^|[^A-Za-z0-9_.])(Navigator\.(push|pop)|MaterialPageRoute)' "Navigator.push/pop, MaterialPageRoute -> context.pushNamed / context.pop"
  ban '(^|[^A-Za-z0-9_.])(showDialog|showModalBottomSheet)(<[^>]*>)?\(' "showDialog()/showModalBottomSheet() -> MaterialDialogRoute<T> / MaterialSheetRoute<T> registered in the router"

  grep -oE 'SizedBox\((height|width): *[0-9][^)]*\)?' "$code" | grep -qv 'child:' \
    && fail "SizedBox(height:/width:) -> spacing: or Dimensions.kGap*"
fi

# --- 6. const new(...) constructors (rules §2) --------------------------------
awk '
  match($0, /^[[:space:]]*(abstract |final |sealed |base |interface |mixin )*class [A-Za-z0-9_]+/) {
    line = $0
    sub(/.*class /, "", line)
    sub(/[^A-Za-z0-9_].*/, "", line)
    cls = line
    next
  }
  cls != "" && $0 ~ ("^[[:space:]]+const " cls "[[:space:]]*[(.]") { found = 1; exit }
  END { exit found ? 1 : 0 }
' "$code" || fail "declare constructors as 'const new(...)', not 'const <ClassName>(...)'"

# --- 7. package barrel stays alphabetical (rules §11) ------------------------
if [ "$zone" = packages ] && [ "$base" = "$self" ]; then
  barrel=$(awk '
    /^export / {
      if (prev != "" && $0 < prev) { print "barrel exports must stay alphabetical (" prev " before " $0 ")"; exit }
      prev = $0
      next
    }
    { prev = "" }
  ' "$code")
  [ -n "$barrel" ] && fail "$barrel"
fi

# --- 8. hardcoded UI text (rules §5) -----------------------------------------
case "$rel" in
  */presentation/*)
    if ! allow l10n-text; then
      grep -oE "Text\([[:space:]]*'[^']+'" "$code" \
        | sed -E "s/^Text\([[:space:]]*'//" \
        | grep -v '\$' | grep -qE "[A-Za-z]{2}" \
        && fail "Text('literal') -> Text(context.l10n.<key>)"
    fi
    ;;
esac

# --- 9. import order (rules §6) ---------------------------------------------
if ! allow import-order; then
  order=$(awk '
    /^import \047dart:/ {
      if (seen_pkg) { print "dart: imports must come before package: imports"; exit }
      next
    }
    /^import \047package:/ {
      seen_pkg = 1
      line = $0
      sub(/^import \047package:/, "", line)
      sub(/\047.*$/, "", line)
      if (prev != "" && line < prev) {
        print "package: imports must be alphabetical (" prev " before " line ")"
        exit
      }
      prev = line
    }
  ' "$code")
  [ -n "$order" ] && fail "$order"
fi

# --- 10. every BlocBuilder/BlocConsumer needs buildWhen (rules §7) -------------
if ! allow build-when; then
  builders=$(grep -cE '\bBloc(Builder|Consumer)<' "$code")
  if [ "$builders" -gt 0 ] && [ "$(grep -c 'buildWhen:' "$code")" -lt "$builders" ]; then
    fail "every BlocBuilder/BlocConsumer needs buildWhen:"
  fi
fi

# --- 11. bloc field shape (rules §5) ------------------------------------------
[ "$bloc_scope" = 1 ] && case "$base" in
  *_bloc)
    bloc_body=$(awk '
      /^[a-z ]*class [A-Za-z0-9_]*Bloc[ <]/ { inside = 1; next }
      inside && /^[a-z ]*class / { exit }
      inside { print }
    ' "$code")
    if ! allow bloc-mutable; then
      printf '%s\n' "$bloc_body" \
        | grep -qE "^  (late )?(List|Map|Set|int|double|bool|String)\b[<>A-Za-z0-9_, ?]*[[:space:]]+[a-zA-Z_][A-Za-z0-9_]*[[:space:]]*(=[^>]|;)" \
        && fail "no mutable state in a bloc -> keep it in the page mixin"
    fi
    if ! allow bloc-public-dep; then
      printf '%s\n' "$bloc_body" \
        | grep -qE "^  final [A-Z][A-Za-z0-9_]*[<>A-Za-z0-9_, ?]*[[:space:]]+[a-z]" \
        && fail "bloc dependencies must be private: 'final GetXxx _getXxx;'"
    fi
    ;;
esac

exit 0
