// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1-E8_GuHEvMjuzNiWd2DhYZ_HWH-c90I',
    appId: '1:738452141157:android:8c5f056b8e363ddca8828c',
    messagingSenderId: '738452141157',
    projectId: 'sample-562f9',
    storageBucket: 'sample-562f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTG3mgzQ1PFau9l6tSH_ABjoNnj0AjV7Q',
    appId: '1:738452141157:ios:3fed86ac6ce84d17a8828c',
    messagingSenderId: '738452141157',
    projectId: 'sample-562f9',
    storageBucket: 'sample-562f9.firebasestorage.app',
    iosBundleId: 'uz.shs.moduleArchitectureFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTG3mgzQ1PFau9l6tSH_ABjoNnj0AjV7Q',
    appId: '1:738452141157:ios:3fed86ac6ce84d17a8828c',
    messagingSenderId: '738452141157',
    projectId: 'sample-562f9',
    storageBucket: 'sample-562f9.firebasestorage.app',
    iosBundleId: 'uz.shs.moduleArchitectureFlutter',
  );
}
