name: navigation
version: 0.0.1
homepage: "none"
publish_to: "none"
description: "A new Flutter project."

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  # external packages
  go_router: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: any

flutter:
  uses-material-design: true
