name: main
description: "A new Flutter project."
version: 0.0.1
homepage: "none"
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  # packages
  core:
    path: ../../packages/core
  navigation:
    path: ../../packages/navigation
  # modules
  more:
    path: ../../modules/more

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
